openapi: 3.1.0
info:
  title: Reverse Proxy's Administration API
  description: Management API for the load balancer to monitor status and manage backend server pools.
  version: 1.0.0
servers:
  - url: http://localhost:8079
    description: Administration Port (Default)
paths:
  /login:
    post:
      tags:
        - Authentication
      summary: Authenticate admin user
      description: Exchange credentials for a JWT bearer token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInput'
      responses:
        '200':
          description: Login successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid username or password.
        '500':
          description: Some error happens Decoding or token generation
  /status:
    get:
      tags:
        - Monitoring
      summary: Get proxy health and backend list
      description: Returns the current status of all backends in the server pool.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Total number of backends, and the number of active backends with a list of backends and their health status.
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Backend'
        '401':
          description: Unauthorized - Invalid or missing token.
        '500':
          description: Some error during marshalling data

  /backends:
    post:
      tags:
        - Management
      summary: Add a new backend
      description: Adds a new server to the server pool.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BackendInput'
      responses:
        '201':
          description: Backend added successfully.
        '400':
          description: Invalid JSON or malformed URL.
        '401':
          description: Unauthorized.

    delete:
      tags:
        - Management
      summary: Remove a backend
      description: Removes an existing server from the load balancer pool.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BackendInput'
      responses:
        '204':
          description: Backend removed successfully.
        '400':
          description: Invalid JSON or malformed URL.
        '401':
          description: Unauthorized.
        '404':
          description: Backend not found in pool.

components:
  schemas:
    LoginInput:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: "admin"
        password:
          type: string
          format: password
          example: "admin"

    LoginResponse:
      type: object
      properties:
        token:
          type: string
          description: JWT token to be used in the Authorization header.
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

    Backend:
      type: object
      properties:
        url:
          type: string
          format: uri
          example: "http://backend-1:8080"
        is_alive:
          type: boolean
          example: true
        last_response_time:
          type: int
          example: 770372
    
    BackendInput:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: uri
          example: "http://backend-1:8080"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: Monitoring
    description: Real-time health and status endpoints.
  - name: Management
    description: Dynamic configuration of the server pool.
